### ISSUE TITLE
Posterior Parameter Access in Python

### ISSUE THREAD

**Issue by amifalk** [promised-ai/lace#124]
In order to use crosscat as a prior for partially-pooled regression/cognitive models, we'd like to be able to access the posterior cluster parameters in Python. 

@BaxterEaves suggested two potential solutions: 

1) We could serialize the metadata from the lace Engine into a .yaml and parse out the values. 
2) More likely, we would want to make a Python binding that pulls from ```lace_cc/state.rs -> feature_as_mixture -> MixtureType```

What's the best way to go about implementing this?

**Comment by amifalk** [comment]
Looks good to me! Presumably we would also allow column index as input like other functions in the python engine class?

**Comment by BaxterEaves** [comment]
Yep. [Here is what I came up with](https://github.com/promised-ai/lace/blob/feature/pylace-component-params/pylace/lace/engine.py#L448-L503). Thoughts?

**Comment by BaxterEaves** [comment]
Functionality merged in with #125
