### ISSUE TITLE
Examples of usage?

### ISSUE THREAD

**Issue by perplexes** [promised-ai/lace#133]
This seems useful but I am not an ML expert. I have done a lot of data analysis in my career. Could you please list some examples of where Lace would be the tool to reach for? Maybe one in academia, one in industry, and one in personal use (like buying something or seeing a surprising pattern in ordinary life)

**Comment by BaxterEaves** [comment]
Thanks! This is a great point. I've started to address it in #134. What do you think of [this text](https://github.com/promised-ai/lace/pull/134/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R128-R149). Is it too jargony?

**Comment by BaxterEaves** [comment]
Resolved with #134 - can reopen if anyone disagrees
