### ISSUE TITLE
Add variance caluclation for specific columns

### ISSUE THREAD

**Issue by schmidmt** [promised-ai/lace#163]
**Is your feature request related to a problem? Please describe.**
Right now, to estimate the variance, you need to use Monte-Carlo estimation via `simulate`.

**Describe the solution you'd like**

The variance of a mixture distribution is simple to calculate if you have access to the mixture components and weights: [see](https://stats.stackexchange.com/questions/16608/what-is-the-variance-of-the-weighted-mixture-of-two-gaussians#answer-16609).

**Comment by BaxterEaves** [comment]
Working on this in #165

**Comment by BaxterEaves** [comment]
Closed in #165
