### ISSUE TITLE
Add method to add columns for the Python API `Engine`

### ISSUE THREAD

**Issue by schmidmt** [promised-ai/lace#90]
There is no way to add a column once an engine is created. An empty `Engine` would be instantiated for the required use case, and custom columns would be added to it.

General idea (not a specification):

```python
from lace import Engine, ColumnType, Normal

eng = Engine()
eng.add_column("column_name", ColumnType.Continuous(Normal.standard()))

eng.add_row({
    "column_name": 1.234,
})
```

**Comment by BaxterEaves** [comment]
This is addressed in #95
